#!/bin/bash
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

getMacIP() {
  CMD="ipconfig getifaddr en0"
  RES=$(eval $CMD)
}


 getLinuxIp() {
 CMD="ip route show"
 OUTPUT=$(eval $CMD)
 first=src
 last=metric
 strindex() {
  x="${1%%$2*}"
  [[ "$x" = "$1" ]] && echo -1 || echo "${#x}"
  }
  firstIndex=$(strindex "$OUTPUT" "$first")
  shortOp=${OUTPUT:$firstIndex}
  lastIndex=$(strindex "$shortOp" "$last")
  RES=${shortOp:3:$lastIndex - 3}
}

  case "$machine" in
  "Mac")    getMacIP
            echo $RES
    ;;
  "Linux")  getLinuxIp
            echo $RES
        ;;
    *) echo "No support for your device yet"
 esac