#!/bin/bash
# CMD="ipconfig getifaddr en0"
# OUTPUT=$(eval $CMD)
# echo $OUTPUT

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac
echo ${machine}