#!/bin/bash
CMD="ifconfig en0"
OUTPUT=$(eval $CMD)
first=192.168.
second=netmask
strindex() {
  x="${1%%$2*}"
  [[ "$x" = "$1" ]] && echo -1 || echo "${#x}"
}
firstIndex=$(strindex "$OUTPUT" "$first")
secondIndex=$(strindex "$OUTPUT" "$second")
diff=$secondIndex-$firstIndex
echo ${OUTPUT:$firstIndex: $diff}